# Generated by Django 3.0.6 on 2020-10-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, default='', null=True)),
                ('phone', models.IntegerField()),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_occupation', to='myapp.Person')),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Person')),
            ],
        ),
    ]
