# Generated by Django 3.0.6 on 2020-10-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201027_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_detail',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_occupation', to='myapp.Person'),
        ),
    ]
